import 'dart:convert';
import 'dart:io';

/// Writes `integration_test/store_captions.dart` from the caption translation
/// journal and the titles in `store/play/source/listing.txt`.
///
///   dart tool/make_store_captions.dart `<captions journal.jsonl>`
///
/// The captions and titles are committed, unlike the rest of the listing:
/// `integration_test/store_screenshots_test.dart` needs them to compile, and
/// CI analyzes that folder. The descriptions and the graphics stay in the
/// gitignored `store/`.
void main(List<String> args) {
  if (args.length != 1) {
    stderr.writeln('usage: make_store_captions.dart <journal.jsonl>');
    exit(2);
  }

  // The app language each Play listing code shows, in Play's order.
  const Map<String, String> stores = <String, String>{
    'en-US': 'en',
    'ar': 'ar',
    'bn-BD': 'bn',
    'zh-CN': 'zh',
    'nl-NL': 'nl',
    'fr-FR': 'fr',
    'de-DE': 'de',
    'hi-IN': 'hi',
    'id': 'id',
    'it-IT': 'it',
    'ja-JP': 'ja',
    'ko-KR': 'ko',
    'pl-PL': 'pl',
    'pt-PT': 'pt',
    'ru-RU': 'ru',
    'es-ES': 'es',
    'th': 'th',
    'tr-TR': 'tr',
    'ur': 'ur',
    'vi': 'vi',
  };

  const List<String> englishCaptions = <String>[
    'Point and scan. QR codes and barcodes.',
    'See where a link goes, before it opens',
    'Risky links are flagged, never opened for you',
    'Create codes that are checked to scan',
    'Everything you scan stays on your phone',
    'Twenty languages. Light and dark.',
    'No ads on the camera or the result',
  ];

  final Map<String, List<String>> byApp = <String, List<String>>{
    'en': englishCaptions,
  };
  for (final String line in File(args[0]).readAsLinesSync()) {
    if (line.trim().isEmpty) continue;
    final Object? row = jsonDecode(line);
    if (row is! Map || row['type'] != 'result') continue;
    final Object? value = row['value'] ?? row['result'];
    final Object? languages = value is Map ? value['languages'] : null;
    if (languages is! List) continue;
    for (final Object? entry in languages) {
      if (entry is! Map) continue;
      byApp[entry['code'] as String] = (entry['captions'] as List<Object?>)
          .map((Object? c) => c! as String)
          .toList();
    }
  }

  // Titles come from the listing, so the feature graphic says exactly what
  // the store page says.
  final Map<String, String> titles = <String, String>{};
  final File listing = File('store/play/source/listing.txt');
  if (!listing.existsSync()) {
    stderr.writeln('store/play/source/listing.txt is missing; build it first');
    exit(1);
  }
  String? code;
  for (final String line in listing.readAsLinesSync()) {
    if (line.startsWith('=== ')) {
      code = line.substring(4).split(' | ')[0].trim();
    }
    if (line.startsWith('title: ') && code != null) {
      titles[code] = line.substring(7);
    }
  }

  String quote(String s) =>
      "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$')}'";

  final StringBuffer out = StringBuffer()
    ..writeln('// GENERATED by tool/make_store_captions.dart. Do not edit.')
    ..writeln('//')
    ..writeln('// The captions printed over the Play screenshots and the title')
    ..writeln('// on the feature graphic, in every listing language. Rebuild:')
    ..writeln('//')
    ..writeln(
      '//   dart tool/make_store_captions.dart <captions journal.jsonl>',
    )
    ..writeln('//')
    ..writeln('// The seven captions are, in order: the five screens of')
    ..writeln('// `_shots`, Settings, and the feature graphic tagline last.')
    ..writeln()
    ..writeln('/// The seven captions for each Play listing language.')
    ..writeln('const Map<String, List<String>> storeCaptions =')
    ..writeln('    <String, List<String>>{');
  final List<String> missing = <String>[];
  for (final MapEntry<String, String> store in stores.entries) {
    final List<String>? captions = byApp[store.value];
    if (captions == null || captions.length != 7) {
      missing.add(store.key);
      continue;
    }
    out.writeln("  '${store.key}': <String>[");
    for (final String caption in captions) {
      out.writeln('    ${quote(caption)},');
    }
    out.writeln('  ],');
  }
  out
    ..writeln('};')
    ..writeln()
    ..writeln("/// Each listing's title, as it appears on the store page.")
    ..writeln('const Map<String, String> storeTitles = <String, String>{');
  for (final String code in stores.keys) {
    final String? title = titles[code];
    if (title == null) {
      missing.add(code);
      continue;
    }
    out.writeln("  '$code': ${quote(title)},");
  }
  out.writeln('};');

  File('integration_test/store_captions.dart')
      .writeAsStringSync(out.toString());
  stdout.writeln(
    '${stores.length - missing.toSet().length}/${stores.length} languages '
    '-> integration_test/store_captions.dart',
  );
  if (missing.isNotEmpty) {
    stderr.writeln('missing: ${missing.toSet().join(', ')}');
    exit(1);
  }
}
